format = """
[░▒▓](#4c0099)\
$time\
[▓▒░](#4c0099)\
\n$username\
$hostname\
[ 󰣇 ](bg:#678DCD fg:#090c0c)\
[](bg:#00BAF9 fg:#678DCD)\
$directory\
[](fg:#00BAF9)\
\n$character"""

[directory]
style = "fg:black bg:#00BAF9"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads "
"music" = " "
"Music" = "  Music "
"Pictures" = " Pictures "
"games" = " "
"desktop" = " "

[username]
show_always = true
style_user = "fg:black bg:#678DCD"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#678DCD fg:black"
format = '[$hostname]($style)'

[time]
disabled = false
#time_format = "%T" # Hour:Minute Format
time_format = "%e-%b-%Y %H:%M" # Hour:Minute Format
#style = "bg:#C4B5A0"
#format = '[[  $time ](fg:#050301 bg:#6666FF)]($style)'
format = '[[  $time ](fg:#fff301 bg:#6666FF)]($style)'
